# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - devtaxreader-001-func

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      toTheMoon:
        description: 'Fire up the rocket to the moon?'
        required: false
        type: boolean

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './gr-gettaxinfo' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.*' # set this to the dotnet version to use

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Workflow is now starting'
        run: |
          echo "Log level: $LEVEL"
          echo "Rocket to the Moon: $MOON"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          MOON: ${{ inputs.toTheMoon }}
          ENVIRONMENT: ${{ inputs.environment }}
  # deploy-job:
  #   runs-on: ubuntu-latest
  #   needs: build-job
  #   steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Setup DotNet ${{ env.DOTNET_VERSION }} Environment'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          # dotnet build --configuration Release --output ./output
          dotnet publish --configuration Release -o '../published-app'
          ls
          ls './published-app'
          popd
  # deploy-job:
  #   runs-on: ubuntu-latest
  #   needs: build-job
  #   steps:
      # - name: 'Resolve Project Dependencies Using Dotnet'
      #   shell: pwsh
      - name: 'Peek into the publication results'
        shell: pwsh '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        run: |
          echo '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          ls
          ls -la
          popd
      # - name: "Pause and Wait for manual approval"
      #   uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: dinos-kon
      #     minimum-approvals: 1
      #     issue-title: "Deploying ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} via ci/cd"
      
      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: echo '${{ toJSON(github) }}'
      # - name: Dump job context
      #   run: echo '${{ toJSON(job) }}'
      # - name: Dump steps context
      #   run: echo '${{ toJSON(steps) }}'
      # - name: Dump runner context
      #   run: echo '${{ toJSON(runner) }}'
      # - name: Dump strategy context
      #   run: echo '${{ toJSON(strategy) }}'
      # - name: Dump matrix context
      #   run: echo '${{ toJSON(matrix) }}'
        
      - name: 'Run Azure Function Deployment Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'devtaxreader-001-func'
          # slot-name: 'Production'
          # package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/published-app'
          package: './published-app'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_10D46073F3E44FAC8671D91BD6B5CB58 }}